(function(){
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const money=n=>'£'+Number(n||0).toFixed(0);
  const getCart=()=>JSON.parse(localStorage.getItem('mm_cart_v3')||'[]');
  const setCart=c=>{localStorage.setItem('mm_cart_v3',JSON.stringify(c));updateCartCount();};
  const findProduct=id=>(window.PRODUCTS||[]).find(p=>p.id===id);
  const imageUrl=p=>{
    const path = p.imagePath || `assets/img/artwork/${p.image}`;
    try { return new URL(path, document.baseURI).pathname + (new URL(path, document.baseURI).search || ''); }
    catch(e) { return path; }
  };
  function toast(msg){let t=$('#toast'); if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)} t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
  function updateCartCount(){const count=getCart().reduce((a,i)=>a+i.qty,0);$$('.cart-count').forEach(x=>x.textContent=count)}
  function addToCart(id,qty=1){const p=findProduct(id); if(!p)return; const c=getCart(); const ex=c.find(i=>i.id===id); if(ex)ex.qty+=qty; else c.push({id,qty}); setCart(c); toast('Added to basket')}
  function removeFromCart(id){setCart(getCart().filter(i=>i.id!==id)); renderCart(); renderCheckoutSummary()}
  function changeQty(id,delta){let c=getCart(); const it=c.find(i=>i.id===id); if(!it)return; it.qty+=delta; if(it.qty<=0)c=c.filter(i=>i.id!==id); setCart(c); renderCart(); renderCheckoutSummary()}
  window.MM={addToCart,removeFromCart,changeQty,getCart};
  function buyLabel(p){
    if(p.id==='clarity-map-print') return 'Order print edition';
    if(p.id==='clarity-map-digital') return 'Order digital clarity map';
    if(p.id==='custom-moment-map-digital') return 'Order digital map';
    if(p.id==='custom-moment-map-physical') return 'Order printed map';
    if(p.id==='custom-moment-card-digital') return 'Order digital card';
    if(p.id==='custom-moment-card-physical') return 'Order printed card';
    if(p.category==='spaces') return 'Enquire / order';
    return p.cta||'Buy securely';
  }
  function shopifySlot(p,cls=''){
    return `<div class="shopify-buy-slot ${cls}" data-shopify-product="${p.id}" data-shopify-label="${buyLabel(p)}"></div>`;
  }
  function productCard(p){return `<article class="product-card ${p.imageAspect==='wide'?'product-card-wide':''}" data-category="${p.category}" data-title="${(p.title+' '+p.subtitle+' '+p.format).toLowerCase()}">
    <a class="product-media" href="product.html?id=${p.id}" aria-label="View ${p.title}"><img src="${imageUrl(p)}" alt="Artwork preview for ${p.title}"></a>
    <div class="product-body"><span class="badge">${p.badge||p.format}</span><a class="product-title" href="product.html?id=${p.id}">${p.title}</a><p class="product-meta">${p.subtitle}</p><div class="option-row"><span class="option">${p.format}</span><span class="option">${p.variant}</span></div><div class="product-foot product-foot-shopify"><strong>${p.priceLabel}</strong>${shopifySlot(p,'shopify-slot-card')}</div></div></article>`}
  function renderFeatured(){const el=$('[data-featured-products]'); if(el)el.innerHTML=(window.PRODUCTS||[]).slice(0,6).map(productCard).join('')}
  function renderArchive(){const el=$('[data-archive-grid]'); if(!el)return; const arts=[1,2,3,4,5,6,7,8,9,10,11,12]; el.innerHTML=arts.map(i=>`<img src="assets/img/artwork/art-${String(i).padStart(2,'0')}-thumb.jpg" alt="Project artwork ${i}">`).join('')}
  function renderShop(){const grid=$('[data-product-grid]'); if(!grid)return; grid.innerHTML=(window.PRODUCTS||[]).map(productCard).join(''); setFilter(new URLSearchParams(location.search).get('category')||'all'); window.MMShopifyRefresh?.()}
  function setFilter(cat){$$('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===cat)); $$('.product-card').forEach(card=>{card.hidden=!(cat==='all'||card.dataset.category===cat)})}
  function renderProduct(){const mount=$('[data-product-detail]'); if(!mount)return; const id=new URLSearchParams(location.search).get('id')||(window.PRODUCTS||[])[0]?.id; const p=findProduct(id); if(!p){mount.innerHTML='<div class="empty-state card"><h1>Product not found</h1><a class="btn btn-primary" href="shop.html">Back to shop</a></div>';return} document.title=p.title+' | Moment & Matter'; const cat=(window.CATEGORIES||[]).find(c=>c.id===p.category); mount.innerHTML=`<div class="breadcrumb"><a href="shop.html">Shop</a> / <a href="shop.html?category=${p.category}">${cat?cat.title:'Products'}</a></div><div class="detail-layout ${p.imageAspect==='wide'?'detail-layout-wide':''}"><div class="detail-image ${p.imageAspect==='wide'?'detail-image-wide':''}"><img src="${imageUrl(p)}" alt="Artwork preview for ${p.title}"></div><article class="detail-panel card"><span class="badge">${p.badge||p.format}</span><h1 class="detail-title">${p.title}</h1><p class="lede">${p.subtitle}</p><div class="detail-price">${p.priceLabel}</div><p>${p.description}</p><div class="option-row"><span class="option">${p.format}</span><span class="option">${p.variant}</span><span class="option">${p.shippingClass==='digital'?'Digital delivery':'Worldwide shipping available'}</span></div><div class="actions shopify-detail-actions">${shopifySlot(p,'shopify-slot-detail')}<a class="btn btn-secondary" href="shop.html">Back to shop</a></div><p class="small muted checkout-note">Payment is completed securely through Shopify. PayPal Express appears at Shopify checkout when enabled in your Shopify payment settings.</p><div class="grid-2" style="margin-top:24px"><div class="card"><h3>Best for</h3><ul class="list-clean">${p.bestFor.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><h3>What arrives</h3><ul class="list-clean">${p.arrives.map(x=>`<li>${x}</li>`).join('')}</ul></div></div></article></div>`; const rel=$('[data-related-products]'); if(rel) rel.innerHTML=(window.PRODUCTS||[]).filter(x=>x.category===p.category&&x.id!==p.id).slice(0,3).map(productCard).join(''); window.MMShopifyRefresh?.()}
  function shippingFor(items,dest){ if(!items.some(i=>i.product.shippingClass!=='digital')) return 0; const classes=new Set(items.map(i=>i.product.shippingClass)); if(dest==='world'){ if(classes.has('space')) return 48; if(classes.has('boxed')) return 28; return 18 } if(classes.has('space')) return 18; if(classes.has('boxed')) return 12; return 6 }
  function totals(){const items=getCart().map(i=>({...i,product:findProduct(i.id)})).filter(i=>i.product); const subtotal=items.reduce((a,i)=>a+i.product.price*i.qty,0); const dest=$('#shippingDestination')?.value||localStorage.getItem('mm_dest')||'uk'; const shipping=shippingFor(items,dest); return {items,subtotal,shipping,total:subtotal+shipping,dest}}
  function summaryHtml(t,href,label){return `<div class="checkout-box"><h3>Order summary</h3>${t.items.map(i=>`<div class="summary-row"><span>${i.qty} × ${i.product.title}</span><strong>${money(i.product.price*i.qty)}</strong></div>`).join('')}<div class="summary-row"><span>Items</span><strong>${money(t.subtotal)}</strong></div><div class="summary-row"><span>Estimated postage</span><strong>${t.shipping?money(t.shipping):'£0'}</strong></div><div class="summary-row total"><span>Total estimate</span><strong>${money(t.total)}</strong></div><a class="btn btn-primary btn-block" href="${href}">${label}</a><p class="small muted" style="margin-top:14px">This creates an order request. Payment can be completed by invoice, payment link, or shop checkout after the details are confirmed.</p></div>`}
  function renderCart(){const el=$('[data-cart]'); if(!el)return; el.innerHTML='<div class="empty-state card"><h1>Checkout now runs through Shopify.</h1><p class="muted">Choose a product below and use the secure Shopify button. PayPal Express will appear at Shopify checkout when enabled.</p><a href="shop.html" class="btn btn-primary">View all offers</a></div>'; const s=$('[data-cart-summary]'); if(s)s.innerHTML=''}
  function renderCheckoutSummary(){const s=$('[data-checkout-summary]'); if(!s)return; s.innerHTML='<div class="checkout-box"><h3>Secure Shopify checkout</h3><p>Use any product button on this page to complete checkout through Shopify.</p><p class="small muted">Digital products do not require shipping. Physical products use your Shopify shipping settings.</p></div>'}
  function checkoutBuyNow(){const id=new URLSearchParams(location.search).get('buy'); if(id&&findProduct(id)){location.href=`product.html?id=${id}`}}
  function orderText(data){const t=totals(); const lines=['Moment & Matter order request','',`Name: ${data.name||''}`,`Email: ${data.email||''}`,`Destination: ${t.dest==='world'?'Worldwide / outside UK':'UK'}`,`Order estimate: ${money(t.total)}`,'','Items:']; t.items.forEach(i=>lines.push(`- ${i.qty} × ${i.product.title} (${i.product.format}) — ${money(i.product.price*i.qty)}`)); lines.push('', 'Notes:', data.notes||''); return lines.join('\n')}
  function bind(){updateCartCount(); const menuBtn=$('#menuBtn'); const mobilePanel=$('#mobilePanel'); menuBtn?.addEventListener('click',()=>{const open=mobilePanel?.classList.toggle('open'); menuBtn.setAttribute('aria-expanded',open?'true':'false')}); document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mobilePanel?.classList.contains('open')){mobilePanel.classList.remove('open'); menuBtn?.setAttribute('aria-expanded','false'); menuBtn?.focus()}}); document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'); if(add){addToCart(add.dataset.add)} const filt=e.target.closest('[data-filter]'); if(filt){setFilter(filt.dataset.filter); history.replaceState(null,'',filt.dataset.filter==='all'?'shop.html':`shop.html?category=${filt.dataset.filter}`)}}); $('#searchProducts')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase(); const cat=$('.filter-btn.active')?.dataset.filter||'all'; $$('.product-card').forEach(card=>{const okCat=cat==='all'||card.dataset.category===cat; const okQ=!q||card.dataset.title.includes(q); card.hidden=!(okCat&&okQ)})}); $('#shippingDestination')?.addEventListener('change',e=>{localStorage.setItem('mm_dest',e.target.value); renderCart(); renderCheckoutSummary()}); const dest=$('#shippingDestination'); if(dest)dest.value=localStorage.getItem('mm_dest')||'uk'; $('#checkoutForm')?.addEventListener('submit',e=>{e.preventDefault(); toast('Checkout is now handled securely through Shopify buttons on the product pages.');}); const orderEl=$('[data-order-number]'); if(orderEl){orderEl.textContent=new URLSearchParams(location.search).get('order')||sessionStorage.getItem('mm_order')||'MM-READY'} const orderTextEl=$('[data-order-text]'); if(orderTextEl){orderTextEl.textContent=sessionStorage.getItem('mm_order_text')||'Your order request will appear here after checkout.'} $('#copyOrder')?.addEventListener('click',async()=>{const txt=$('[data-order-text]')?.textContent||''; try{await navigator.clipboard.writeText(txt); toast('Copied order request')}catch(e){toast('Select and copy the request text')}}); $('#customBriefForm')?.addEventListener('submit',e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target).entries()); const txt=`Custom piece request\n\nName: ${d.name||''}\nEmail: ${d.email||''}\nPiece type: ${d.type||''}\nFormat: ${d.format||''}\nWho or what is this for: ${d.for||''}\nMoment: ${d.moment||''}\nTone: ${d.tone||''}\nWhat should not be said: ${d.avoid||''}`; const out=$('#briefOutput'); if(out){out.textContent=txt; out.hidden=false; $('#copyBrief')?.removeAttribute('hidden')}}); $('#copyBrief')?.addEventListener('click',async()=>{const txt=$('#briefOutput')?.textContent||''; try{await navigator.clipboard.writeText(txt); toast('Copied brief')}catch(e){toast('Select and copy the brief text')}})}
  document.addEventListener('DOMContentLoaded',()=>{bind(); renderFeatured(); renderArchive(); renderShop(); renderProduct(); checkoutBuyNow(); renderCart(); renderCheckoutSummary(); window.MMShopifyRefresh?.()})
})();
